### ISSUE TITLE
Absolute Poll in Google Chat can't create pool and add new option

### ISSUE THREAD

**Issue by quynhlm** [dyaskur/google-chat-poll#27]
After enter the poll topic and options, click Submit can't create a poll and when create poll by mentioning @Absolute Poll with question and answers, i can't add new option.

**Comment by dyaskur** [comment]
Hi @quynhlm ,

Thank you for sharing your concern here. Regrettably, I am unable to reproduce the issue you're facing. I can successfully create a poll using the form and add options to it. To better assist you, could you provide more details or possibly a screenshot of the problem you're encountering? Your additional information will help me replicate the issue and find a solution.

**Comment by quynhlm** [comment]
Hi @dyaskur 
Thanks for your reply, I have a video I was reproduced that issue.

https://github.com/dyaskur/google-chat-poll/assets/144432786/53f8a99c-2f96-408c-999b-9b4217ed05b7

**Comment by dyaskur** [comment]
Thank you for providing more information. I have to admit, I still cannot replicate the issue. However, based on the video that you shared, it seems that the app does not work when it calls the Google API. I found this error log in the console:

> This organization’s administrator must allow users to install this Chat app 

This suggests that your Google Workspace administrator has not enabled the installation of third-party applications. To fix this, you may need to ask your admin to follow these instructions: https://support.google.com/a/answer/7651360?hl=en

However, if the current setting is already enabled, then it means that the error is coming from Google Chat (Alphabet Inc) itself.

In the meantime, I have found a workaround to solve this problem using action response triggers. So, I will try to allow user use my application without the needs to enable 3rd-party setting.

Thank you again for your report. I was aware of some similar error logs, but thanks to you I now know the root cause. I hope it can be resolved soon.

**Comment by dyaskur** [comment]
I've pushed the workaround. You should now be able to create a poll using the poll command. Let me know if you still have any issues or concerns.

Thanks

**Comment by quynhlm** [comment]
@dyaskur  I tested it and it was successful, thanks for your great support !
