### ISSUE TITLE
Fail in scheduler to close the poll

### ISSUE THREAD

**Issue by patrick-cardoso** [dyaskur/google-chat-poll#30]
Hello

Here in Brazil, where our time zone is GMT -3, automatic closing does not work.
The scheduler doesn't save the set value.

Thank you

**Comment by dyaskur** [comment]
Thank you for reporting your issue. I have successfully replicated it and will work on resolving it promptly. It appears in [this line](https://github.com/dyaskur/google-chat-poll/blob/master/src/handlers/ActionHandler.ts#L74) I used the wrong operator; it should be a subtraction (-) instead of an addition (+) .

**Comment by dyaskur** [comment]
I've applied the necessary update to rectify the issue. With this fix, the auto-close feature should now operate as anticipated in your time zone.

Thank you, and please don't hesitate to reach out if you have any questions or concerns.

**Comment by privatechate** [comment]
Good

**Comment by Sefasizz** [comment]
🧡👍
